### ISSUE TITLE
tag ci fails in build step

### ISSUE THREAD

**Issue by kulmann** [owncloud/web-extensions#17]
I've crafted a release `external-sites-v0.1.0`, see https://github.com/owncloud/web-extensions/releases/tag/external-sites-v0.1.0
The Release title and description are already adjusted manually, but here's what happened:

1. release CI failed in `build` pipeline:
https://drone.owncloud.com/owncloud/web-extensions/89/3/7
with
```console
+ cd assets/extensions
/bin/sh: cd: line 42: can't cd to assets/extensions: No such file or directory
```
As a result the release didn't have a .zip artifact attached.

2. release title was modified to `None refs/tags/external-sites-v0.1.0` (no idea why)

See screenshot for the state after CI adjusted it:

<img width="950" alt="Screenshot 2024-07-25 at 06 14 49" src="https://github.com/user-attachments/assets/2c478160-5855-4221-a5b2-7c452bf2af6b">

**Comment by dschmidt** [comment]
I see. I think... the package step needs to depends_on the build steps or quickfix: the build steps need to have the delends_on: pnpm-install removed (so they build in serial again)
