### ISSUE TITLE
Add e2e tests to CI

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web-extensions#35]
https://github.com/owncloud/web-extensions/pull/32 #102  introduced e2e tests, now they need to be added to CI.

**Comment by JammingBen** [comment]
@ScharfViktor I guess we can close this since the CI is implemented?

**Comment by ScharfViktor** [comment]
> @ScharfViktor I guess we can close this since the CI is implemented?

yes. thanks for remind me 👍
