### ISSUE TITLE
Add CI for translations

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web-extensions#40]
Apps need to be added to Transifex and CI needs to be in place to push and pull new translations.

**Comment by mmattel** [comment]
This needs to be done in a way where the resource on transifex gets a clear identifyer that it is not web but an extension. In ocis, we name the server tx `ocis-xxx`. With that, one can easily filter and identify them.

**Comment by kulmann** [comment]
Aware of that. I was thinking about 'web-extensions-' (the repo name) as prefix per resource. Same needs to be applied for the resorces from 'web-' at some point in the future.

**Comment by mmattel** [comment]
> Same needs to be applied for the resorces from 'web-' at some point in the future.

This is a great point!

`web-`
`web-extensions-`
`ocis-` (could be added, because we need to 'migrate' the server resoures from the current location)

**Comment by kulmann** [comment]
this is done
