### ISSUE TITLE
Resource naming for translations will not work as expected

### ISSUE THREAD

**Issue by mmattel** [owncloud/web-extensions#97]
Referencing: #94 (ci: set up translation sync)

@kulmann the attempt naming the resource will not work.

Pls have a look at https://owncloud.dev/services/general-info/add-translations/
There you will see how we integrated from the ocis side.

Example:
**wrong**
```
[o:owncloud-org:p:owncloud-web:r:web-extensions-cast]
file_filter = locale/<lang>/app.po
minimum_perc = 0
source_file = template.pot
source_lang = en
type = PO
```
**correct** (add resource_name)
```
[o:owncloud-org:p:owncloud-web:r:web-extensions-cast]
file_filter = locale/<lang>/app.po
minimum_perc = 0
resource_name = web-extensions-cast
source_file = template.pot
source_lang = en
type = PO
```

**Comment by kulmann** [comment]
resource_name is only needed for the initial setup. I changed them manually in transifex. You can check there. Works as intended, only that I had the additional effort of renaming the resources once (which was indeed annoying).

**Comment by mmattel** [comment]
We ran thru the same issue, but when we planned adding another resource, I found out how to do it properly and we changed it in the definition without going to TX.

I highly recommend doing this here too because if another web extension is added, one can template it and does not need raised grants on TX. It just appears as it should.

**Comment by kulmann** [comment]
I agree that it makes sense to add the names to the source. Feel free to make a PR, I will happily review it.
The statement that this PR doesn't work is not true though. ;-)
